# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04
  
steps:
- bash: |
    # install BATS
    sudo apt-get install bats

    # install shellcheck
    export scversion="v0.5.0"
    wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-"${scversion}".linux.x86_64.tar.xz" | tar -xJv
    cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    shellcheck --version

    # set environment variables
    echo "##vso[task.setvariable variable=PATH]$PATH:$PWD/drwc:$PWD/shellcheck-"${scversion}"/shellcheck:."
  displayName: 'Set up testing environment'

- bash: |
    make
  displayName: 'Build drwc to check for errors'
  workingDirectory: $(Build.SourcesDirectory)/drwc

- bash: |
    tests/test_dr
  displayName: 'Run bats tests'

- bash: |
    shellcheck dr
  displayName: 'Run shellcheck'