# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- bash: |
    make
  displayName: 'Build drwc to check for errors'
  workingDirectory: $(Build.SourcesDirectory)/drwc

- bash: |
    sudo apt-get install bats
    PATH="$PATH:." tests/test_dr
  displayName: 'Run bats tests'

- bash: |
    sudo apt-get install shellcheck
    shellcheck dr
  displayName: 'Run shellcheck'