# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04
  
steps:
- bash: |
    # install BATS
    sudo apt-get install bats

    # install shellcheck
    export scversion="v0.5.0"
    wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-"${scversion}".linux.x86_64.tar.xz" | tar -xJv

    # set environment variables
    # Our shellcheck comes before system shellcheck
    # (as they already have one on the MS image that's a painfully old version).
    echo "##vso[task.setvariable variable=PATH]$PWD/shellcheck-"${scversion}":$PATH:$PWD/drwc:."
  displayName: 'Set up testing environment'

- bash: |
    shellcheck --version
    shellcheck dr
  displayName: 'Run shellcheck'

- bash: |
    make
  displayName: 'Build drwc to check for errors'
  workingDirectory: $(Build.SourcesDirectory)/drwc

- bash: |
    tests/test_dr
  displayName: 'Run bats tests'