# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- bash: |
    export DEBIAN_FRONTEND=noninteractive # make apt-get shut up
    DEBIAN_FRONTEND=noninteractive sudo apt-get install bats shellcheck
  displayName: 'Install shell analysis and testing tools'

- bash: |
    make
  displayName: 'Build drwc to check for errors'
  workingDirectory: $(Build.SourcesDirectory)/drwc

- bash: |
    shellcheck dr
  displayName: 'Run shellcheck'

- bash: |
    export PATH="$PATH:./drwc:."
    tests/test_dr
  displayName: 'Run bats tests'